sudo: false
language: android
dist: trusty
android:
  components:
    - tools
    - build-tools-30.0.0
    - android-30

before_install: 
 - chmod +x gradlew
 - yes | sdkmanager "platforms;android-30"
 
script: ./gradlew assembleRelease --stacktrace

licenses:
 - '.+'
